### 什么是panic？
是一种在我们意料之外的程序异常,这种程序异常被叫做 panic，这种异常只会在程序运行的时候被抛出来。常见的有数组越界异常。当 panic 被抛出之后，如果我们没有在程序里添加任何保护措施的话，程序就会在打印出 panic 的详细情况之后，终止运行。

### 从 panic 被引发到程序终止运行的大致过程是什么？
- 某个函数中的某行代码有意或无意地引发了一个 panic。这时，初始的 panic 详情会被建立起来，并且该程序的控制权会立即从此行代码转移至调用函数的那行代码上，也就是调用栈中的上一级。
- 这也意味着，此行代码所属函数的执行随即终止。紧接着，控制权并不会在此有片刻的停留，它又会立即转移至再上一级的调用代码处。控制权如此一级一级地沿着调用栈的反方向传播至顶端，也就是我们编写的最外层函数那里。这里的最外层函数指的是go函数，对于主 goroutine 来说就是main函数。
- 但是控制权也不会停留在那里，而是被 Go 语言运行时系统收回。随后，程序崩溃并终止运行，承载程序这次运行的进程也会随之死亡并消失。
- 与此同时，在这个控制权传播的过程中，panic 详情会被逐渐地积累和完善，并会在程序终止之前被打印出来。

### 如何在程序中主动抛出异常
- panic 可能是我们在无意间引发的，如索引越界。这类 panic 是真正的、在我们意料之外的程序异常。
- 不过，除此之外，我们还是可以有意地引发 panic。Go 语言的内建函数`panic`是专门用于引发 panic 的。panic函数使程序开发者可以在程序运行期间报告异常。
- 注意，这与从函数返回错误值的意义是完全不同的。当我们的函数返回一个非nil的错误值时，函数的调用方有权选择不处理，并且不处理的后果往往是不致命的。“不致命”的意思是，不至于使程序无法提供任何功能（也可以说僵死）或者直接崩溃并终止运行（也就是真死）。
- 但是，当一个 panic 发生时，如果我们不施加任何保护措施，那么导致的直接后果就是程序崩溃，这显然是致命的。

